language: r
cache:
  packages: true
  directories:
  - $TRAVIS_BUILD_DIR/_bookdown_files
sudo: false
before_script:
- chmod +x ./deployment/_build.sh
- chmod +x ./deployment/_deploy.sh
script:
- travis_wait 45 "./deployment/_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deployment/_deploy.sh
env:
  global:
  - secure: Bjy+ctO2APj70fIJnJju9bCXQHYQbvKiPsV59EmUjYRq13cXtq0S3zyxwG7H6cgnnAWTl4/zWtHHY6b3VdCYo2uAnptB82EUqfCywaldFxVdOo1wojcn/OY2nK/noafs4JBewhlXv+RHGeDfaylniV4EiyRrlM5agR4R4/m5X2KyyTH0KVYxeMM6S+gBcIqtgPA1XDWIp70+DjAaO/WesdHaFEINFSZaj0u4WlJ9IZpnDia17FLSZSZIRaeLNlmun1KApTFagwma5PREij8WxowNMt8lR9DQ71j34RYlFDoQt+VCVxIUOKJ/aPzPnxEfT3EJV6TujMXgHi7KMUnXXFcfSEaFni3wUBx3ZVyOEsoXmJ/3P4cK3WE9vSRAaaAPNLkB3Yq/a8f//gpfbHLP57ZqjdgIjP7KOrpdNwWqX0wyow9voMzk8u82lX4rSkCR42Urb6FtVPGxgNC0gOr9hai9vrBGgZsTwhOGLLtBUCRsKuMtgUqgsZ/g7my1ce7+OW8UlsRYLmsIXUD9xmhxSHkVVyJqF686DIbKmBqvtOoaScEvVAJitAJrO6dM8BAudhs6RYOQIAN/jwLb8E9h8cqqDz++P4iblstEfr+orXKZOKDHRXC3NiTcN2NJdg9QGJ5+cbyL3OPt4McOjcW6OWhBTUf4XfjXMkLHLqKBmdQ=
