language: r
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
sudo: false
before_script:
- chmod +x ./deployment/_build.sh
- chmod +x ./deployment/_deploy.sh
script:
- travis_wait 45 "./deployment/_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deployment/_deploy.sh
env:
  global:
    secure: eYSjfs6FZ/jL8TwTmI4szv6JW0/T9CtbPdrHQc6sgGn0vVaT8PinSsOe8nqIDfrI9Q9bTRML3dabRfIGcqBWKbFFHOXeoqxjSi0CGuJafJKppyLuW1E+9eghi9foIexHWKFjm8Q3JtaO+HyYczKMagNsmDD0WmwbMYnNw1H/rOM48LXiCUyZZnBeNVE4GASUubcim0ihen4j0kmiPit8qWKQb4mCLLRlhzeOvvbPNYcFxG2xvc+qQNq3093FOUraLMjbez2f34gQmKhjqn/RFnvx3emv15csj51EI5lIg9yqlDfQhlXuKYPK28ydwfrqpIrYNO3iv+qVtYZLreGchwKDCCqwWTH54TWNRxi30EPQGjPMygv1D6q232MRzHCcmFixZjrzhqtzxLDlL8Lq5kpJMuXqRqjBtYj+I/655ycFiZy+jNbb5S0KQnnbUnEAe/I9neEyqB4SZRkD6yIQnh3W3HQZ5aQzjd6MBiG67HJfuHpu1C6HzwmvrHmVLaZrWaEF4+iOKyMDHJADuXZcDRloQpqr1gmPDX9Z/9kQaE9x6GFBgMoV36PKRcuRyvl8iKsp8ElV/dmaScqrQ2ZqVHdvcZ0FZdalh8nAhuPrp+UWG+iY8hwGNRutauHSSXLQ1qqqF0QBPlMQr0sG+TXyhn0XQG5AxWV543SAO0nDx0o=
