language: r
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
sudo: false
before_script:
- chmod +x ./deployment/_build.sh
- chmod +x ./deployment/_deploy.sh
script:
- travis_wait 45 "./deployment/_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  deployment/_deploy.sh
env:
  global:
    secure: RqaDG+DUGiHuiVs18GvXac8NT/2lstAaWW+R3KMmDUH+fRlAD+gPrjqR9sGWPXfeqIL1Xg5KQnyEIgB1sI+J41O7uTsAeJTLN3t+zetGRQH81hmIAnOJ4VA2ki7U7ZQNYHOL9DrcQcNwDTnfV2P9nXS2zYbrPCBw5hjTrg3vnfre4dF1eJebvo+qOZEGlYodoL+CaZbjHYSiEKyXZ85B1fPuQVltErJvCPyqjbNLFzGjpB2qz98RuDDHkMO1Hlatv7aOYmcc08Z9GiH5xyYrvniEA+g4FRBgQTK0g8+X3rJVTx9qatG6/LLqFicmln39xud9/mogDAg8ec/rjMgTpdFAgoyaJBK2Sg45Cyrvf2Sb05eFvaXCJY/e2lSwVuGuJzly/xiCo8Uf5JpkoTtsAy9vxCb/ACcWK91iOrQ9P1IF+us6QckCkLabfwrsfSdZJT7OiIN8LGBTP88nz51Gqf/KOKMthlOI5IkSebWLsTkveeNo6y+IChQnCop9VWmb+W6Cpwbl4zLhSEyr9zSSzBxpZ+YiP1F4JOxO8V8U60hAmX/MipPqfzSc5oXyWpeUeI/cHwcQAgiEPI08TPnnvAvMvzXZvZxuA5oY0qbz661bGUpXPpevZtQyZOYQPmt72h+/Z5Aj138tIKRa4R+IScAL71IrgQhZYj2Jd/Pn5eM=
